In [2]:
import numpy as np


In [4]:
import sys
!{sys.executable} -m pip install torch==1.7.1



ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\hxi00\Anaconda\lib\site-packages\pip\_internal\cli\base_command.py", line 188, in main
    status = self.run(options, args)
  File "C:\Users\hxi00\Anaconda\lib\site-packages\pip\_internal\commands\install.py", line 345, in run
    resolver.resolve(requirement_set)
  File "C:\Users\hxi00\Anaconda\lib\site-packages\pip\_internal\legacy_resolve.py", line 196, in resolve
    self._resolve_one(requirement_set, req)
  File "C:\Users\hxi00\Anaconda\lib\site-packages\pip\_internal\legacy_resolve.py", line 362, in _resolve_one
    dist = abstract_dist.get_pkg_resources_distribution()
  File "C:\Users\hxi00\Anaconda\lib\site-packages\pip\_internal\distributions\wheel.py", line 14, in get_pkg_resources_distribution
    self.req.source_dir))[0]
IndexError: list index out of range


In [ ]:
!{sys.executable} -m pip install torchvision

In [7]:
import torch
import torchvision

In [8]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)

tensor([[1, 2],
        [3, 4]])


In [18]:
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_rand)

tensor([[0.4039, 0.8429],
        [0.0861, 0.5394]])


In [26]:
shape = (2,3,)
rand_tensor = torch.rand(shape)
zero_tensor = torch.zeros(shape)
print(rand_tensor, "\n",zero_tensor)

tensor([[0.2181, 0.7065, 0.1902],
        [0.3521, 0.5216, 0.7754]]) 
 tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [30]:
zero_tensor = torch.zeros(4,4)
zero_tensor[:, 1] = 2
print(zero_tensor)

tensor([[0., 2., 0., 0.],
        [0., 2., 0., 0.],
        [0., 2., 0., 0.],
        [0., 2., 0., 0.]])


In [31]:
if torch.cuda.is_available():
  tensor = tensor.to('cuda')

In [35]:
t1 = torch.cat([zero_tensor, zero_tensor], dim = 0)
print(t1)

tensor([[0., 2., 0., 0.],
        [0., 2., 0., 0.],
        [0., 2., 0., 0.],
        [0., 2., 0., 0.],
        [0., 2., 0., 0.],
        [0., 2., 0., 0.],
        [0., 2., 0., 0.],
        [0., 2., 0., 0.]])


In [40]:
t_mul = zero_tensor * t_mul
print(t_mul)
t_matmul = zero_tensor.matmul(zero_tensor)
print(t_matmul)

tensor([[ 0., 16.,  0.,  0.],
        [ 0., 16.,  0.,  0.],
        [ 0., 16.,  0.,  0.],
        [ 0., 16.,  0.,  0.]])
tensor([[0., 4., 0., 0.],
        [0., 4., 0., 0.],
        [0., 4., 0., 0.],
        [0., 4., 0., 0.]])


In [45]:
print(t_mul)
t_mul.add_(5)
print(t_mul)
print(t_mul.t_())

tensor([[15., 31., 15., 15.],
        [15., 31., 15., 15.],
        [15., 31., 15., 15.],
        [15., 31., 15., 15.]])
tensor([[20., 36., 20., 20.],
        [20., 36., 20., 20.],
        [20., 36., 20., 20.],
        [20., 36., 20., 20.]])
tensor([[20., 20., 20., 20.],
        [36., 36., 36., 36.],
        [20., 20., 20., 20.],
        [20., 20., 20., 20.]])


In [47]:
t = torch.ones(5,5)
t.add_(1)
print(t)
n = t.numpy()
print(n)

tensor([[2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.],
        [2., 2., 2., 2., 2.]])
[[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]


In [50]:
n = np.ones((5,4))
np.add(n, 1, out = n)
print(n)
t = torch.from_numpy(n)
print(t)

[[2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]
 [2. 2. 2. 2.]]
tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]], dtype=torch.float64)


'{sys.executable}' is not recognized as an internal or external command,
operable program or batch file.
